# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0c9c66cef17a173f8dabff2bd6077d3f60d5e58c1c6b873256c26b910d72634c125220d3c86e47e65cd7e7c969cc16a9ab39051770eb991f9db16e4180915d10

test:
  secret_key_base: 786235e198ca5c0fc86847c111f4d9a3f9c29301bfcff1aa0d0555546662af30c0c7e4342a34100fdf7558f014173d2880cf323a1af15d44eef5c492ffc844ae

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
